### ISSUE TITLE
Athlete id is modeled as an integer (i.e. Java client becomes Integer)

### ISSUE THREAD

**Issue by loopyzort** [strava/developers.strava.com#14]
https://github.com/strava/developers.strava.com/blob/master/swagger/athlete.json.mustache#L6

Thus far, we've been modeling most ids like this as `Long`s or `int64` to prevent any capacity issues down the road.

**Comment by mindy-stivers** [comment]
Thanks for bringing this up! I'm going to close the issue on this page and move it for tracking elsewhere.
