### ISSUE TITLE
API possibility to search activities

### ISSUE THREAD

**Issue by Cooluck** [strava/developers.strava.com#26]
Please add to API a possibility to search public activities

Reference in web version: https://www.strava.com/activities/search?utf8=%E2%9C%93&location=%D0%9A%D0%B8%D0%B5%D0%B2%2C+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%9A%D0%B8%D0%B5%D0%B2%2C+%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&%5Bcountry%5D=Ukraine&%5Bstate%5D=&%5Bcity%5D=Kiev&%5Blat_lng%5D=50.4501%2C30.523400000000038&keywords=Wizzair+Marathon&activity_type=Run&type=&distance_start=38&distance_end=44&time_start=0&time_end=10&elev_gain_start=0&elev_gain_end=5000

**Comment by mindy-stivers** [comment]
Thanks for the suggestion! There aren't plans to implement this today, but I'll make sure to bring it up with the team.

Sorry it took a few months to notice this issue - we have several communication channels and meant to have github issues disabled.  If you have questions or suggestions in the future, please send them in to api@strava.com
