### ISSUE TITLE
Delete Activity (deleteActivityById) Authorization Error

### ISSUE THREAD

**Issue by matthewspencer** [strava/developers.strava.com#32]
Greetings!

When trying to [delete an activity](https://developers.strava.com/docs/reference/#api-Activities-deleteActivityById) I get the following authorization error:

```json
{
  "message": "Authorization Error",
  "errors": [
    {
      "resource": "Application",
      "field": "delete",
      "code": "forbidden"
    }
  ]
}
```

Is there an additional `scope` to [request](https://developers.strava.com/docs/authentication/#request-access) for a user besides `write` to allow for deletion?

**Comment by mindy-stivers** [comment]
Hi @matthewspencer, sorry it took a few months to notice this issue - we have several communication channels and meant to have github issues disabled. 

You're correct - deletion is not part of the `write` scope for API applications.

If you have follow-up questions, please send them in to api@strava.com
