### ISSUE TITLE
Please provide a valid Android config.json that matches the production sample documentation

### ISSUE THREAD

**Issue by atofallis** [strava/developers.strava.com#69]
I've tried to build local jar/aar libraries to integrate with a 'hello world' Strava Android app, however I've come across several issues. The last time I checked the Libraries section, there were a bunch of 3rd party references (I was looking at https://github.com/SweetzpotAS/StravaZpot-Android , for example). Since these references have been removed, I've been scratching my head a little on how to replace my 3rd party lib dependency with a newly generated 'source of truth'. 

The first pain-point I had was trying to get a local environment up and running. I eventually gave up and downloaded the latest swagger-codegen-cli jar from maven [here](https://mvnrepository.com/artifact/io.swagger/swagger-codegen-cli/2.3.1)

Running the following commands appeared to generate successfully:
```
java -jar swagger-codegen-cli-2.3.1.jar generate -i https://developers.strava.com/swagger/swagger.json -l android -o strava-android
java -jar swagger-codegen-cli-2.3.1.jar generate -i https://developers.strava.com/swagger/swagger.json -l java -o strava-java
```

However this just doesn't work. Android (gradle bump and a few trivial compilation fixes aside) aar fails to merge dex with some apache http library issues, and the Java lib builds but the API looks nothing like the sample suggestion [here](https://developers.strava.com/docs/reference/) (createService() is not part of the API, for example)

Swagger FAQ gets me one step closer, suggesting to explicitly use volley for Android, or other options for Java (I try retrofit2 next):
https://github.com/swagger-api/swagger-codegen/wiki/FAQ#android

However the aforementioned [sample code](https://developers.strava.com/docs/reference/) expects an Observable return type from ActivitiesApi createActivity(), so I need to configure the generator to use RxJava. 
StackOverflow leads me to create and specify e.g. config as follows:
rxJava.json:
```
{
  "library": "retrofit2",
  "artifactId": "swagger-strava-retrofit2-rx",
  "useRxJava": true,
  "hideGenerationTimestamp": true
}
```

`java -jar swagger-codegen-cli-2.3.1.jar generate -i https://developers.strava.com/swagger/swagger.json -l java -o strava-retrofit2-rx -c path-to-config\rxJava.json`

All seems to look much better, but I still get a runtime exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/threeten/bp/format/DateTimeFormatter;
   at io.swagger.client.JSON$OffsetDateTimeTypeAdapter.<init>(JSON.java:108)
   at io.swagger.client.JSON.<init>(JSON.java:46)
   at io.swagger.client.ApiClient.createDefaultAdapter(ApiClient.java:105)
   at io.swagger.client.ApiClient.<init>(ApiClient.java:41)
```

I'm simply calling testCode() within onCreate of an Activity that otherwise starts up fine. Again, this is just a compilation fix of the Java 'Create an activity' sample from [here](https://developers.strava.com/docs/reference/) :

```
private void testCode() {
    ApiClient client = new ApiClient();
    ActivitiesApi api = client.createService(ActivitiesApi.class);

    String name = "name_example"; // String | The name of the activity.
    String type = "type_example"; // String | Type of activity. For example - Run, Ride etc.
    String startDateLocal = "startDateLocal_example"; // String | ISO 8601 formatted date time.
    Integer elapsedTime = 56; // Integer | In seconds.
    String description = "description_example"; // String | Description of the activity.
    String distance = "distance_example"; // String | In meters.
    Integer privateActivity = 56; // Integer | set to 1 to mark the resulting activity as private, ‘view_private’ permissions will be necessary to view the activity. If not specified, set according to the athlete’s privacy setting (recommended).
    Integer trainer = 56; // Integer | Set to 1 to mark as a trainer activity.
    String photoIds = "photoIds_example"; // String | List of native photo ids to attach to the activity.
    Integer commute = 56; // Integer | Set to 1 to mark as commute.

    Observable<DetailedActivity> result = api.createActivity(name, type, startDateLocal, elapsedTime, description, distance, privateActivity, trainer, photoIds, commute);
    result.subscribe(System.out::println, Throwable::printStackTrace);
}
```

Assuming this did actually work at runtime, IMO the documentation around integrating OAuth is a little short (at least, for now, the 3rd party library [LoginResult](https://github.com/SweetzpotAS/StravaZpot-Android/blob/master/README.md#obtain-a-token) wrapper seems to work, and I can't find any reference indicating that a successful OAuth returns a Token + Athlete object)

The current README.md does mention an android.json config file, but there is only a html one [here](https://github.com/strava/developers.strava.com/tree/master/config)

I was hoping my weekend of poking around would lead to a functioning PR, unfortunately did not get that far hence raising this as an issue.

Any feedback greatly appreciated.
Many thanks!

**Comment by atofallis** [comment]
For reference, my android library attempt with the following config / generation command:
`volleyRx.json` : 
```
{
  "library": "volley",
  "artifactId": "swagger-strava-volley-rx",
  "useRxJava": true,
  "hideGenerationTimestamp": true
}
```

`java -jar swagger-codegen-cli-2.3.1.jar generate -i https://developers.strava.com/swagger/swagger.json -l android -o strava-volley-rx -c path-to-config\volleyRx.json`

Project fails to sync with old gradle version specified in gradle-wrapper.properties so I bump this to v4.1 (I'm using Android Studio 3.0.1)

`jarRelease` gradle task fails with compilation error in ExplorerSegment.java (number prefixes are illegal identifiers):
```
  public enum ClimbCategoryDescEnum {
     NC,  4,  3,  2,  1,  HC, 
  };
```

Next, JsonUtil.java is missing io.swagger.client.model.Error required @L85:
```
    if ("Error".equalsIgnoreCase(className)) {
      return new TypeToken<List<Error>>(){}.getType();
    }
```

Seems volley + rxJava was asking for too much, as the return type is now just a DetailedActivity (and there are still a bunch of apache http library dependencies in the project). Running this slightly modified code (no ApiClient any more?) gives me a new runtime exception:
```
    private void testCode() {
        ActivitiesApi api = new ActivitiesApi();

        String name = "name_example"; // String | The name of the activity.
        String type = "type_example"; // String | Type of activity. For example - Run, Ride etc.
        String startDateLocal = "startDateLocal_example"; // String | ISO 8601 formatted date time.
        Integer elapsedTime = 56; // Integer | In seconds.
        String description = "description_example"; // String | Description of the activity.
        String distance = "distance_example"; // String | In meters.
        Integer privateActivity = 56; // Integer | set to 1 to mark the resulting activity as private, ‘view_private’ permissions will be necessary to view the activity. If not specified, set according to the athlete’s privacy setting (recommended).
        Integer trainer = 56; // Integer | Set to 1 to mark as a trainer activity.
        String photoIds = "photoIds_example"; // String | List of native photo ids to attach to the activity.
        Integer commute = 56; // Integer | Set to 1 to mark as commute.

        DetailedActivity result = null;
        try {
            result = api.createActivity(name, type, startDateLocal, elapsedTime, description, distance, privateActivity, trainer, photoIds, commute);
        } catch (TimeoutException | ExecutionException | InterruptedException | ApiException e) {
            e.printStackTrace();
        }
        Log.d(TAG, result.toString());
    }
```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/Consts;
   at io.swagger.client.ApiInvoker.<clinit>(ApiInvoker.java:69)
   at io.swagger.client.ApiInvoker.getInstance(ApiInvoker.java:228)
   at io.swagger.client.api.ActivitiesApi.<init>(ActivitiesApi.java:47)
```

**Comment by mindy-stivers** [comment]
Hi @atofallis, sorry we missed spotting this issue.  We've got several communication channels and actually meant to have github issues disabled.  I'm going to close this issue as part of cleanup.  

If you're still having trouble with this, could you send an email to api@strava.com?   If you figured out a workaround, feel free to submit a pull request.
