### ISSUE TITLE
Removed athlete specific information/profile images

### ISSUE THREAD

**Issue by markdjthomas** [strava/developers.strava.com#72]
As of "Jan 17, 2018", I see in the change-logs that "any information specific to a given athlete now requires authentication". BTW, I didn't notice this until today... even though the change-log states January.

Was there any specific reason for this change?
Is there any way of gathering info of the club members in a club that you maintain?

Personally, I was using the GET club activities and GET club members in order to populate a d3 bubble chart for my running club's homepage. Unfortunately, this is not possible anymore 👎 

http://dartmouthrunners.com/#strava

**Comment by mindy-stivers** [comment]
Hi Mark, sorry we didn't spot this ticket earlier.  We're actually closing all github issues and disabling the feature.

Please email api@strava.com if you still have questions about the club endpoint.
