### ISSUE TITLE
Python authentication example doesn't work

### ISSUE THREAD

**Issue by sshevlyagin** [strava/developers.strava.com#80]
The code in your example doesn't work:
```
swagger_client.configuration.access_token = 'YOUR_ACCESS_TOKEN'
api_instance = swagger_client.AthletesApi()
```
I kept getting auth errors saying the token was invalid.

To get it to work I had to do the following:
```
config = strava_api_v3.Configuration()
config.access_token = 'YOUR_ACCESS_TOKEN'
api_client = strava_api_v3.ApiClient(config)
api_instance = strava_api_v3.AthletesApi(api_client)
athlete = api_instance.get_logged_in_athlete()
```

**Comment by mindy-stivers** [comment]
Hi @sshevlyagin, please feel free to submit a pull request with your workaround for review.

Apologies for not spotting this issue sooner, we're trying to move away from github issues.  In light of that, please email api@strava.com if you have further comments or questions!
