### ISSUE TITLE
gear_id is missing from the SummaryActivity object

### ISSUE THREAD

**Issue by sshevlyagin** [strava/developers.strava.com#81]
gear_id is missing from the SummaryActivity object in the swagger

**Comment by mindy-stivers** [comment]
Hi @sshevlyagin, as with your other issue, please feel free to submit a pull request with your workaround for review.

Apologies for not spotting this issue sooner, we're trying to move away from github issues. In light of that, please email api@strava.com if you have further comments or questions!
